INSERT INTO quote (quote, author)
VALUES
  ('Go second mid, then first mid, then jungle, then B.', 'gL'),
  ('Kurwa... Ja pierdolę.', 'tallah'),
  ('Оеёй, другалёчек!', 'Lunza'),
  ('Fucking game.', 'V1nt'),
  ('Понял?', 'ArtGame'),
  ('Hey, homeless.', 'K@FF33'),
  ('Zaebis!', 'K@FF33'),
  ('Hellooooo!', 'nooby'),
  ('I am not bothered.', 'nooby'),
  ('Я сверху.', 'Souffle'),
  ('Чё за бот такой тупой?', 'Osas'),
  ('СОНЯ КОПИТАН!', 'Osas'),
  ('Работай сука. Тут тебе не плачут.', 'Osas'),
  ('Blyat! Pizdec!', 'st4r'),
  ('We are professionals.', 'st4r'),
  ('Да иди ты на хуй!', 'Di'),
  ('Я за ящик.', 'hydro'),
  ('Я просто танцую.', 'Pashy'),
  ('Алло!?', 'Anime'),
  ('Домой!', 'Anime'),
  ('По пульке стреляйте.', 'PAK'),
  ('Kill him.', 'Keep'),
  ('s1mple.', 'Keep'),
  ('На америке надо по пульке стрелять.', 'PAK'),
  ('На хуй Калаш, Галил ебашит.', 'Di'),
  ('И ни одной моей цитаты... Ну и пожалуйста, блть, ну и пошло всё в пизду, нахуя мне это надо...', 'Lamochina'),
  ('Bluu dor!', 'GoGy'),
  ('Пёс ебучий!', 'Empty'),
  ('See you tomorrow.', 'Alex Yao'),
  ('Jebany fart.', 'tallah'),
  ('Do you need a chair?🪑', 'tallah'),
  ('NANAX2STRONG.', 'tallah'),
  ('Give info please!', 'Di'),
  ('Good morning friends. I wish you a healthy and happy day.', 'Aqua|Deniz'),
  ('Good morning friends. Wishing you a joyful and loving day.', 'Aqua|Deniz'),
  ('My birthday is July 30th.', 'Ruruy'),
  ('Нахуй я смок купил, не знаю. Сохранить?', 'st4r'),
  ('Я это запикаю.', 'PAK'),
  ('Ya!', 'Alex Yao'),
  ('Чё он за мифозник такой?!', 'ImBatyshka'),
  ('O my God, it''s beautiful!', 'Bosco'),
  ('Na na huy!', 'Bosco'),
  ('Это психологическое давление.', 'Di'),
  ('Да ёшкин-матрёшкин!', 'gL'),
  ('Бог наградил меня интеллектом, как у Гарри Каспарова.', 'gL'),
  ('Это так не работает.', 'gL'),
  ('Ну тогда во второй команде два без голоса.', 'Di'),
  ('Может сами поделите?', 'Di'),
  ('Да блять, делите сами!', 'Di'),
  ('Fuck you, bitch!', 'barisbaba'),
  ('Who wanna call?', 'st4r'),
  ('Что же вы творите-то?', 'ImBatyshka'),
  ('Эх, вы!', 'ImBatyshka'),
  ('Всё-таки, я ненавижу Nuke.', 'V1nt'),
  ('Подсадишь меня?', 'vic'),
  ('Иди сюда, подсажу.', 'Angellama'),
  ('Сосать, уроды! Сосать!', 'ceh9'),
  ('Мы чемпионы СНГ!', 'ceh9'),
  ('Шо?!', 'markeloff'),
  ('Сразу в ебало!', 'Zeus'),
  ('You are bad teammaker.', 'tallah'),
  ('Poshel na huy suka blyat!', 'Bosco'),
  ('Davai.', 'evendren'),
  ('I just took a shower.', 'evendren'),
  ('Poshel na huy!', 'evendren'),
  ('Good call, Simon.', 's1m0Ng'),
  ('Вечер в хату!', 'TaHkuCT'),
  ('MUYA VERNITE NAHYI!!!!', 'TaHkuCT'),
  ('Teams unbalanced.', 'blackzer0'),
  ('Shit!', 'PAK'),
  ('Minatooo.', 'coby'),
  ('?', 'Shkodran Mustafi'),
  ('А я вам сейчас покажу...', 'TaHkuCT'),
  ('Я ему ещё хаешку в сраку дал!', 'TaHkuCT'),
  ('What is the next map?', 'Alex Yao'),
  ('Стакнитесь на А, я на Б пошёл.', 'fuz'),
  ('Pishkaaaaaa!', 'fuz'),
  ('Wazuuuuuup!', 'fuz'),
  ('Wooohoooo!', 'Bella Witchy'),
  ('Oh, tallah, it''s you?!', 'Bella Witchy'),
  ('Fucking bot can u make normal teams?', 'Bella Witchy'),
  ('Kick this bot from nanaX i say many time).', 'Bolyarin'),
  ('Fucking hell.', 'yUGi'),
  ('glhf, Babyysss!', 'Shadow King'),
  ('Первая тима сильнее.', 'Angellama'),
  ('Try to hear sounds of cats like "meow".', 'PAK'),
  ('Ты чё ебанулся?', 'st4r'),
  ('Ooooooooooooooooo.', 'darkij'),
  ('Скинуть юсп?', 'Souffle'),
  ('Ooo!', 'Souffle'),
  ('Надо забирать пацана.', 'Letho'),
  ('Он неопасный.', 'Empty'),
  ('Нет, я не пойду, нахуй пошёл он.', 'Empty'),
  ('O my Lord...', 'kecha'),
  ('Одну, по фастику.', 'Empty'),
  ('Where is my money?', 'Edu'),
  ('I am a noob.', 'Ness'),
  ('У меня мышка не стреляет!', 'Ruruy'),
  ('Сейчас я дам энтри в аппсах.', 'Fen9l'),
  ('Hey, Jigar!', 'luemmel'),
  ('Я купаться пошёл.', 'Ruruy'),
  ('У меня интернет вырубили.', 'Ruruy'),
  ('Забери админку у V1nt''а.', 'Lunza'),
  ('У меня интернет вырубили.', 'Lunza'),
  ('У меня свет вырубили.', 'Ruruy'),
  ('У меня свет вырубили.', 'Lunza'),
  ('Эта игра была похожа на смех над человеком.', 'Nepstar'),
  ('I''m here to say hello.', 'MrBrain'),
  ('ERROR! ERROR! ERROR! ERROR! ERROR! = 0 pts.', 'NanaX Community Bot'),
  ('Eto pizdec.', 'F-TeN'),
  ('Есть чё пострелять?', 'antivolt');
