(ns commands.gg
  (:require ["discord.js" :as discord]
            [cljs.core.async :refer [go]]
            [cljs.core.async.interop :refer-macros [<p!]]))

(def builder
  (.. (discord/SlashCommandBuilder.)
      (setName "gg")
      (setDescription "Save the match result!")))

(defn interact! [interaction]
  (let [map-select (.. (discord/StringSelectMenuBuilder.)
                  (setCustomId "map-select")
                  (setPlaceholder "Select a map")
                  (addOptions (.. (discord/StringSelectMenuOptionBuilder.)
                                  (setLabel "Nuke") ; TODO add options from DB
                                  (setValue "Nuke")
                                  )
                              (.. (discord/StringSelectMenuOptionBuilder.)
                                  (setLabel "Inferno")
                                  (setValue "Inferno")
                                  ))
                  )
        team1 (.. (discord/UserSelectMenuBuilder.)
                        (setCustomId "team1")
                        (setPlaceholder "Select players from Team 1")
                        (setMinValues 2) ; TODO change to 5 players
                        (setMaxValues 2))
        team1-score (.. (discord/StringSelectMenuBuilder.)
                        (setCustomId "team1-score")
                        (setPlaceholder "Select the score of Team 1")
                        (addOptions (.. (discord/StringSelectMenuOptionBuilder.)
                                        (setLabel "1") ; TODO add options from DB
                                        (setValue "1")
                                        )
                                    (.. (discord/StringSelectMenuOptionBuilder.)
                                        (setLabel "2")
                                        (setValue "2")
                                        )
                                    (.. (discord/StringSelectMenuOptionBuilder.)
                                        (setLabel "3")
                                        (setValue "3")
                                        )
                                    (.. (discord/StringSelectMenuOptionBuilder.)
                                        (setLabel "4")
                                        (setValue "4")
                                        )
                                    (.. (discord/StringSelectMenuOptionBuilder.)
                                        (setLabel "5")
                                        (setValue "5")
                                        )
                                    (.. (discord/StringSelectMenuOptionBuilder.)
                                        (setLabel "6")
                                        (setValue "6")
                                        )
                                    (.. (discord/StringSelectMenuOptionBuilder.)
                                        (setLabel "7")
                                        (setValue "7")
                                        )
                                    (.. (discord/StringSelectMenuOptionBuilder.)
                                        (setLabel "8")
                                        (setValue "8")
                                        )
                                    (.. (discord/StringSelectMenuOptionBuilder.)
                                        (setLabel "9")
                                        (setValue "9")
                                        )
                                    (.. (discord/StringSelectMenuOptionBuilder.)
                                        (setLabel "10")
                                        (setValue "10")
                                        )
                                    (.. (discord/StringSelectMenuOptionBuilder.)
                                        (setLabel "11")
                                        (setValue "11")
                                        )
                                    (.. (discord/StringSelectMenuOptionBuilder.)
                                        (setLabel "12")
                                        (setValue "12")
                                        )
                                    (.. (discord/StringSelectMenuOptionBuilder.)
                                        (setLabel "13")
                                        (setValue "13")
                                        )
                                    (.. (discord/StringSelectMenuOptionBuilder.)
                                        (setLabel "14")
                                        (setValue "14")
                                        )
                                    (.. (discord/StringSelectMenuOptionBuilder.)
                                        (setLabel "15")
                                        (setValue "15")
                                        )
                                    (.. (discord/StringSelectMenuOptionBuilder.)
                                        (setLabel "16")
                                        (setValue "16")
                                        )
                                    (.. (discord/StringSelectMenuOptionBuilder.)
                                        (setLabel "17")
                                        (setValue "17")
                                        )
                                    (.. (discord/StringSelectMenuOptionBuilder.)
                                        (setLabel "18")
                                        (setValue "18")
                                        )
                                    (.. (discord/StringSelectMenuOptionBuilder.)
                                        (setLabel "19")
                                        (setValue "19")
                                        )
                                    (.. (discord/StringSelectMenuOptionBuilder.)
                                        (setLabel "20")
                                        (setValue "20")
                                        )
                                    (.. (discord/StringSelectMenuOptionBuilder.)
                                        (setLabel "21")
                                        (setValue "21")
                                        )
                                    (.. (discord/StringSelectMenuOptionBuilder.)
                                        (setLabel "22")
                                        (setValue "22")
                                        )
                                    (.. (discord/StringSelectMenuOptionBuilder.)
                                        (setLabel "23")
                                        (setValue "23")
                                        )
                                    (.. (discord/StringSelectMenuOptionBuilder.)
                                        (setLabel "24")
                                        (setValue "24")
                                        )
                                    (.. (discord/StringSelectMenuOptionBuilder.)
                                        (setLabel "25")
                                        (setValue "25")
                                        )
                                    )
                  )
        team2 (.. (discord/UserSelectMenuBuilder.)
                        (setCustomId "team2")
                        (setPlaceholder "Select players from Team 2")
                        (setMinValues 2)
                        (setMaxValues 2))
        button-save (.. (discord/ButtonBuilder.)
                        (setCustomId "test")
                        (setLabel "Save")
                        (setStyle (.-Success discord/ButtonStyle)))
        row-map-select (.addComponents (discord/ActionRowBuilder.) map-select)
        row-team1 (.addComponents (discord/ActionRowBuilder.) team1)
        row-team1-score (.addComponents (discord/ActionRowBuilder.) button-save)
        ]
     ; (.addComponents modal row)
     ; (.showModal interaction modal)
     (.reply interaction #js {:content "hello" :components #js
                              [row-map-select row-team1 row-team1-score] :ephemeral true})
    ))
